# _config.yml
theme_color: snowwhite
brand_color: orangered
content_width: 920px

click_to_top:
  light:
    background_color: "#ffffff"
    color: "#454545"
  dark:
    background_color: "#34323d"
    color: "#bbb"

selection:
  color: "#FFFFFF"
  background_color: "#000000"
  
title: Yuginara
email: ""
description: A poet who serves under the moonlight's call.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yugicchi.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yugicchi
github_username:  yugicchi

theme: minima
plugins:
  - jekyll-feed
remote_theme: "jeffreytse/jekyll-theme-yat"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
